version: 2.1

executors:
  docker-dind:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: false
    resource_class: xlarge
    environment:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build_and_push:
    executor: docker-dind
    steps:
      - checkout

      - run:
          name: Log in to Private Registry
          command: |
            echo "$REGISTRY_PASSWORD" | docker login registry.hearmemanai.xyz --username "$REGISTRY_USERNAME" --password-stdin

      - run:
          name: Build & push wan22 image
          command: |
            # Use the git tag as the Docker image tag
            TAG="${CIRCLE_TAG}"
            if [ -z "$TAG" ]; then
              echo "Error: CIRCLE_TAG is not set. This job should be triggered by a git tag."
              exit 1
            fi

            IMG="registry.hearmemanai.xyz/wan22/wan22-bot"

            docker build --progress=plain -t "${IMG}:${TAG}" .

            docker push "${IMG}:${TAG}"

workflows:
  version: 2
  build_on_tag:
    jobs:
      - build_and_push:
          context: docker-hub
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/  # matches tags like v1, v2.3, v10.0.1
            branches:
              ignore: /.*/
